# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  better-sqlite3 = {
    pname = "better-sqlite3";
    version = "12.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/better-sqlite3/-/better-sqlite3-12.5.0.tgz";
      sha256 = "sha256-CjzQVUsGPDGFuZEu9wWbhEVaLkEdY3+qAWb++f76BMI=";
    };
  };
  codex-cli = {
    pname = "codex-cli";
    version = "0.105.0";
    src = fetchurl {
      url = "https://github.com/openai/codex/archive/refs/tags/rust-v0.105.0.tar.gz";
      sha256 = "sha256-Mn5dBBhxEpuGMNCQevsmalG7IwGgvPp4mT3uGIJIhMk=";
    };
  };
  codex-cli-lockfile = {
    pname = "codex-cli-lockfile";
    version = "0.105.0";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/openai/codex/rust-v0.105.0/codex-rs/Cargo.lock";
      sha256 = "sha256-b0wETiqKjNEoHBg23l9Ypqxg5kCXQhPM5UKpYwMvrnA=";
    };
  };
  codex-dmg = {
    pname = "codex-dmg";
    version = "0.1.0";
    src = fetchurl {
      url = "https://persistent.oaistatic.com/codex-app-prod/Codex.dmg";
      sha256 = "sha256-+Zv1I5HAMjXQzdpt5DxKquncOJmDRT/Cwa6Z9c5SsUA=";
    };
  };
  node-pty = {
    pname = "node-pty";
    version = "1.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/node-pty/-/node-pty-1.1.0.tgz";
      sha256 = "sha256-x1F/GQg93LBfJ2kEaA6ysRprXsq3eLjk5WhabWRbP2A=";
    };
  };
}
