# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  better-sqlite3 = {
    pname = "better-sqlite3";
    version = "12.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/better-sqlite3/-/better-sqlite3-12.5.0.tgz";
      sha256 = "sha256-CjzQVUsGPDGFuZEu9wWbhEVaLkEdY3+qAWb++f76BMI=";
    };
  };
  codex-dmg = {
    pname = "codex-dmg";
    version = "0.1.0";
    src = fetchurl {
      url = "https://persistent.oaistatic.com/codex-app-prod/Codex.dmg";
      sha256 = "sha256-+Zv1I5HAMjXQzdpt5DxKquncOJmDRT/Cwa6Z9c5SsUA=";
    };
  };
  node-pty = {
    pname = "node-pty";
    version = "1.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/node-pty/-/node-pty-1.1.0.tgz";
      sha256 = "sha256-x1F/GQg93LBfJ2kEaA6ysRprXsq3eLjk5WhabWRbP2A=";
    };
  };
}
