# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  better-sqlite3 = {
    pname = "better-sqlite3";
    version = "12.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/better-sqlite3/-/better-sqlite3-12.8.0.tgz";
      sha256 = "sha256-JgKlcm0KnY5r5AfFm8El5gURDtqOOwTn741t33YskSI=";
    };
  };
  codex-dmg = {
    pname = "codex-dmg";
    version = "0.1.0";
    src = fetchurl {
      url = "https://persistent.oaistatic.com/codex-app-prod/Codex.dmg";
      sha256 = "sha256-WSs2iN4Ojk0Ky2FlGsOc8CayZaFHio9Wse+YbpFUE2Y=";
    };
  };
  node-pty = {
    pname = "node-pty";
    version = "1.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/node-pty/-/node-pty-1.1.0.tgz";
      sha256 = "sha256-x1F/GQg93LBfJ2kEaA6ysRprXsq3eLjk5WhabWRbP2A=";
    };
  };
}
